/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import Classes.BusinessCustomer;
import Classes.Loader;
import Classes.PersonalCustomer;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author smart view
 */
public class CustomerSettings extends javax.swing.JPanel {

    /**
     * Creates new form CustomerSettings
     */
    public CustomerSettings(String id, int i) throws FileNotFoundException {
        initComponents();
        selector = i;
        dm = (DefaultTableModel) loginHtable.getModel();
        li.loginH();
        loginH = li.return_loginH();
        for(String obj : loginH)
        {
            String[] split = obj.split("~");
            if(split[0].equals(id))
            {
                dm.addRow(new Object[]{split[1], split[2]});
            }
        }
        if(selector == 1 )
        {
        userID = id;
        li.BusinessCustomer();
        bClist = li.return_business();
        divisionLabel.setVisible(false);
        securityQLabel.setVisible(false);
        securityAnsLabel.setVisible(false);
        zipLabel.setVisible(false);
        divisionField.setVisible(false);
        securityQCombo.setVisible(false);
        securityAnswer.setVisible(false);
        zipField.setVisible(false);
        for(BusinessCustomer obj : bClist)
        {
            if(obj.getID().equals(userID))
            {
               fName = obj.getName();
               nameField.setText(fName);
               contact = obj.get_mobile();
               contactField.setText(contact);
                addr = obj.get_address();
                addrField.setText(addr);
                em = obj.get_email();
                emailField.setText(em);
                pass = obj.get_password();
                c = obj.get_Jdate();
            }
        }
        }
        else
        {
        userID = id;
        li.PersonalCustomer();
        pClist = li.return_personal();
        for(PersonalCustomer obj : pClist)
        {
            if(obj.getID().equals(userID))
            {
               fName = obj.getName();
               nameField.setText(fName);
               contact = obj.get_mobile();
               contactField.setText(contact);
                addr = obj.get_address();
                addrField.setText(addr);
                div = obj.get_division();
                divisionField.setText(div);
                em = obj.get_email();
                emailField.setText(em);
                zip  = obj.get_zip();
                zipField.setText(Integer.toString(zip));
                pass = obj.get_password();
                securityQ = obj.get_securityQ();
                securityQCombo.setSelectedItem(securityQ);
                securityAns  = obj.get_securityAns();
                securityAnswer.setText(securityAns);
                gm  = obj.get_gender();
                d = obj.get_birthDate();
                c = obj.get_Jdate();
            }
        }  
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        oldPassLabel = new javax.swing.JLabel();
        newPassLabel = new javax.swing.JLabel();
        oldPassField = new javax.swing.JPasswordField();
        newPassField = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        divisionLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        zipLabel = new javax.swing.JLabel();
        securityQLabel = new javax.swing.JLabel();
        securityAnsLabel = new javax.swing.JLabel();
        securityQCombo = new javax.swing.JComboBox<>();
        emailField = new javax.swing.JTextField();
        contactField = new javax.swing.JTextField();
        addrField = new javax.swing.JTextField();
        securityAnswer = new javax.swing.JTextField();
        zipField = new javax.swing.JTextField();
        divisionField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        loginHtable = new javax.swing.JTable();

        jTabbedPane1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N

        jPanel1.setLayout(new java.awt.GridBagLayout());

        nameLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        nameLabel.setText("New Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(119, 249, 0, 0);
        jPanel1.add(nameLabel, gridBagConstraints);

        passLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        passLabel.setText("Type your  password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 249, 0, 0);
        jPanel1.add(passLabel, gridBagConstraints);

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 184;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(119, 50, 0, 0);
        jPanel1.add(nameField, gridBagConstraints);

        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 184;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 50, 0, 0);
        jPanel1.add(passField, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(0, 153, 51));
        jButton1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 166, 132, 132);
        jPanel1.add(jButton1, gridBagConstraints);

        jTabbedPane1.addTab("Change Username", jPanel1);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        oldPassLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        oldPassLabel.setText("Current Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(136, 245, 0, 0);
        jPanel2.add(oldPassLabel, gridBagConstraints);

        newPassLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        newPassLabel.setText("New Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 247, 0, 0);
        jPanel2.add(newPassLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 163;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(140, 4, 0, 214);
        jPanel2.add(oldPassField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 163;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 4, 0, 214);
        jPanel2.add(newPassField, gridBagConstraints);

        jButton2.setBackground(new java.awt.Color(0, 153, 102));
        jButton2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton2.setText("Done");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 82, 88, 214);
        jPanel2.add(jButton2, gridBagConstraints);

        jTabbedPane1.addTab("Change Password", jPanel2);

        jLabel2.setText("Address");

        divisionLabel.setText("Division");

        jLabel4.setText("Email");

        jLabel5.setText("Contact Number");

        zipLabel.setText("Zip Code");

        securityQLabel.setText("Security Question");

        securityAnsLabel.setText("Security Answer");

        securityQCombo.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        securityQCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your pets name?", "What is the password of your cellphone?", "Do you trust yourself?" }));

        emailField.setText("jTextField1");

        contactField.setText("jTextField1");

        addrField.setText("jTextField1");

        securityAnswer.setText("jTextField1");

        zipField.setText("jTextField1");

        divisionField.setText("jTextField1");

        jButton3.setText("Done");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(securityAnsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(securityAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(divisionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(divisionField, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(zipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(zipField, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(securityQLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(securityQCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addrField, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(contactField, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(236, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(161, 161, 161))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addrField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(securityQLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(securityQCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(securityAnsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(securityAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(divisionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisionField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ChangeOther Details", jPanel4);

        loginHtable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginHtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Login Date", "Login time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(loginHtable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(343, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Login History", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents
public void start_Update()
     {
        SwingWorker<Boolean,Void> worker = new SwingWorker<Boolean,Void>(){
            @Override
            public Boolean doInBackground() throws Exception{
                String fileName = "";
                if(selector==1)
                {
                fileName="BusinessCustomer.bin";
                }
                else
                {
                fileName="PersonalCustomer.bin"; 
                }
               File file = new File (fileName);
                ObjectOutputStream out = null;
                    try{
                        out = new ObjectOutputStream (new FileOutputStream (fileName, false));
                        if(selector ==1)
                        {
                        for(BusinessCustomer obj: bClist)
                        {
                        out.writeObject(obj);    
                        }
                        }
                        else
                        {
                        for(PersonalCustomer obj: pClist)
                        {
                        out.writeObject(obj);    
                        }    
                        }
                        out.flush ();
                    }catch (Exception e){
                        //e.printStackTrace ();
                    }finally{
                        try{
                            if (out != null) out.close();
                        }catch (Exception e){
                            //e.printStackTrace();
                        }
        }
         
                return true;
            }

       
        };
        worker.execute(); 
     }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean name = false, password = false;
        if(nameField.getText().equals(""))
        {
            nameLabel.setForeground(Color.red);
            nameField.requestFocus();
        }
        else
        {
            nameLabel.setForeground(Color.black);
            name = true;
        }
        if(passField.getPassword().length == 0)
        {
            passLabel.setForeground(Color.red);
            passField.requestFocus();
        }
        else
        {
            passLabel.setForeground(Color.black);
            
            if(selector == 1)
            {
            for(BusinessCustomer obj : bClist)
            {
                if(obj.getID().equals(userID) && obj.get_password().equals(String.valueOf(passField.getPassword())))
                {
                    password = true;
                }
                else
                {
                    passLabel.setForeground(Color.red);
                }
            }
            }
            else
            {
               for(PersonalCustomer obj : pClist)
            {
                if(obj.getID().equals(userID) && obj.get_password().equals(String.valueOf(passField.getPassword())))
                {
                    password = true;
                }
                else
                {
                    passLabel.setForeground(Color.red);
                }
            } 
            }
        }
        if(name == true && password == true)
        {
       
        if(selector == 1)
        {
            Iterator<BusinessCustomer> bCitr = bClist.iterator(); 
            while(bCitr.hasNext())
            {
                BusinessCustomer delbC = bCitr.next();
                if(delbC.getID().equals(userID))
                {
                    bCitr.remove();
                }
            }
            bC = new BusinessCustomer();
             bC.updateAccounts(userID, nameField.getText(), contactField.getText(), addrField.getText(), "", emailField.getText(), 0000, pass, "", "", "", d,c, "" , "" , LocalTime.MAX, LocalTime.MIN, 0, "");
             bClist.add(bC);
             start_Update();
        }
        else
        {
            Iterator<PersonalCustomer> pCitr = pClist.iterator(); 
            while(pCitr.hasNext())
            {
                PersonalCustomer delpC = pCitr.next();
                if(delpC.getID().equals(userID))
                {
                    pCitr.remove();
                }
            }
            pC = new PersonalCustomer();
             pC.updateAccounts(userID, nameField.getText(), contact, addr, div, em, zip, pass, securityQ, securityAns, gm, d,c, "" , "" , LocalTime.MAX, LocalTime.MIN, 0, "");
             pClist.add(pC);
             start_Update();
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    boolean passCheck(char[] pass)
    {
        boolean foundUpper = false, foundLower = false, foundAlpha = false;
        
        if(pass.length<8)
        {
            return false;
        }
        
        for(int i = 0; i<pass.length; i++)        
        {
            if(Character.isAlphabetic(pass[i]))
            {
                foundAlpha = true;
                if(Character.isUpperCase(pass[i]))
                {
                    foundUpper = true;
                }
                else
                {
                    foundLower = true;
                }
            }
        }
        if(foundUpper == true && foundLower == true && foundAlpha == true)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean oldPass = false, newPass = false;
        if(oldPassField.getPassword().length == 0)
        {
            oldPassField.setForeground(Color.red);
            oldPassField.requestFocus();
        }
        else
        {
          passLabel.setForeground(Color.black);
          if(selector ==1)  
          {
          for(BusinessCustomer obj : bClist)
            {
                if(obj.get_password().equals(String.valueOf(oldPassField.getPassword())) && obj.getID().equals(userID))
                {
                    oldPass = true;
                }
                else
                {
                    passLabel.setForeground(Color.red);
                }
            }
          }
          else
          {
              for(PersonalCustomer obj : pClist)
            {
                if(obj.get_password().equals(String.valueOf(oldPassField.getPassword())) && obj.getID().equals(userID))
                {
                    oldPass = true;
                }
                else
                {
                    passLabel.setForeground(Color.red);
                }
            }
          }
        
        }
        if(newPassField.getPassword().length == 0)
        {
           newPassField.setForeground(Color.red);
           newPassField.requestFocus();
        }
        else if(passCheck(newPassField.getPassword()) == false)
        {
           newPassField.setBackground(Color.red);
           newPassField.requestFocus();
        }
        else
        {
            newPassField.setForeground(Color.black);
            newPassField.setBackground(Color.black);
            newPass = true;      
        }
        
        if(selector == 1)
        {
            Iterator<BusinessCustomer> bCitr = bClist.iterator(); 
            while(bCitr.hasNext())
            {
                BusinessCustomer delbC = bCitr.next();
                if(delbC.getID().equals(userID))
                {
                    bCitr.remove();
                }
            }
            bC = new BusinessCustomer();
             bC.updateAccounts(userID, fName, contact, addr, "", em, 0000, String.valueOf(newPassField.getPassword()), "", "", "", d,c, "" , "" , LocalTime.MAX, LocalTime.MIN, 0, "");
             bClist.add(bC);
             start_Update();
        }
        else
        {
            Iterator<PersonalCustomer> pCitr = pClist.iterator(); 
            while(pCitr.hasNext())
            {
                PersonalCustomer delpC = pCitr.next();
                if(delpC.getID().equals(userID))
                {
                    pCitr.remove();
                }
            }
            pC = new PersonalCustomer();
             pC.updateAccounts(userID, fName, contact, addr, div, em, zip, String.valueOf(newPassField.getPassword()), securityQ, securityAns, gm, d,c, "" , "" , LocalTime.MAX, LocalTime.MIN, 0, "");
             pClist.add(pC);
             start_Update();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if(selector == 1)
        {
            Iterator<BusinessCustomer> bCitr = bClist.iterator(); 
            while(bCitr.hasNext())
            {
                BusinessCustomer delbC = bCitr.next();
                if(delbC.getID().equals(userID))
                {
                   bCitr.remove();
                }
            }
            bC = new BusinessCustomer();
             bC.updateAccounts(userID, nameField.getText(), contactField.getText(), addrField.getText(), "", emailField.getText(), 0000, pass, "", "", "", d,c, "" , "" , LocalTime.MAX, LocalTime.MIN, 0, "");
             bClist.add(bC);
             start_Update();
        }
        else
        {
            Iterator<PersonalCustomer> pCitr = pClist.iterator(); 
            while(pCitr.hasNext())
            {
                PersonalCustomer delpC = pCitr.next();
                if(delpC.getID().equals(userID))
                {
                   pCitr.remove();
                }
            }
            pC = new PersonalCustomer();
            
             pC.updateAccounts(userID, nameField.getText(), contactField.getText(), addrField.getText(), divisionField.getText(), emailField.getText(), Integer.parseInt(zipField.getText()), pass, securityQCombo.getItemAt(securityQCombo.getSelectedIndex()), securityAnswer.getText(), gm, d,c, "" , "" , LocalTime.MAX, LocalTime.MIN, 0, "");
             pClist.add(pC);
             start_Update();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldActionPerformed
   Loader li = new Loader();
   ArrayList<BusinessCustomer> bClist = new ArrayList<>();
    ArrayList<PersonalCustomer> pClist = new ArrayList<>();
    ArrayList<String> loginH = new ArrayList<>();
    BusinessCustomer bC;
    PersonalCustomer pC;
   String userID, fName, contact, addr, div, em, pass,  securityQ,  securityAns,  gm;
   int zip, selector =0;
    LocalDate d = null, c = null;
    DefaultTableModel dm;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrField;
    private javax.swing.JTextField contactField;
    private javax.swing.JTextField divisionField;
    private javax.swing.JLabel divisionLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable loginHtable;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField newPassField;
    private javax.swing.JLabel newPassLabel;
    private javax.swing.JPasswordField oldPassField;
    private javax.swing.JLabel oldPassLabel;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel securityAnsLabel;
    private javax.swing.JTextField securityAnswer;
    private javax.swing.JComboBox<String> securityQCombo;
    private javax.swing.JLabel securityQLabel;
    private javax.swing.JTextField zipField;
    private javax.swing.JLabel zipLabel;
    // End of variables declaration//GEN-END:variables
}
