/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import Classes.AirCargoPilot;
import Classes.BusinessCustomer;
import Classes.HubAdmin;
import Classes.HubStaff;
import Classes.Loader;
import Classes.LorryPilot;
import Classes.Owner;
import Classes.PersonalCustomer;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author smart view
 */
public class ForgotFrame extends javax.swing.JFrame {

    /**
     * Creates new form ForgotFrame
     */
   
    public ForgotFrame() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ansLabel = new javax.swing.JLabel();
        tComboBox = new javax.swing.JComboBox<>();
        qComboBox = new javax.swing.JComboBox<>();
        ansField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        idField = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel1.setText("Account type:");

        jLabel2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel2.setText("Security Question:");

        ansLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ansLabel.setText("Answer:");

        tComboBox.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        tComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Owner", "Personal", "Staff", "Hub Admin" }));

        qComboBox.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        qComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your pets name?", "What is the password of your cellphone?", "Do you trust yourself?" }));

        jButton1.setBackground(new java.awt.Color(0, 153, 51));
        jButton1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton1.setText("Get!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        idLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        idLabel.setText("Enter Your ID:");

        jButton2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton2.setText("Return");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel3.setText("If you own a Business Account please contact us through email to validate proof");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(ansLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(ansField, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(292, 292, 292)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(37, 37, 37)
                                .addComponent(qComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ansLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ansField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String password = "";
        if(idField.getText().equals(""))
        {
            idLabel.setForeground(Color.red);
            idField.requestFocus();
        }
        else if (ansField.getText().equals(""))
        {
            ansLabel.setForeground(Color.red);
            ansField.requestFocus();
        }
        else
        {
           idLabel.setForeground(Color.black);
           ansLabel.setForeground(Color.black);
            if(tComboBox.getItemAt(tComboBox.getSelectedIndex()).equals("Owner"))
            {
                 li.Owner();
                 oWlist = li.return_Owner();
                 for(Owner obj : oWlist)
                 {
                     if(obj.getID().equals(idField.getText()) && obj.get_securityQ().equals(qComboBox.getItemAt(qComboBox.getSelectedIndex())) && obj.get_securityAns().equals(ansField.getText()))
                     {
                         password = obj.get_password();
                     }
                 }
            }
            else if(tComboBox.getItemAt(tComboBox.getSelectedIndex()).equals("Hub Admin"))
            {
                 li.HubAdmins();
                 hAlist = li.return_hubAdmin();
                 for(HubAdmin obj : hAlist)
                 {
                     if(obj.getID().equals(idField.getText()) && obj.get_securityQ().equals(qComboBox.getItemAt(qComboBox.getSelectedIndex())) && obj.get_securityAns().equals(ansField.getText()))
                     {
                         password = obj.get_password();
                     }
                 }    
            }
            else if(tComboBox.getItemAt(tComboBox.getSelectedIndex()).equals("Personal"))
            {
                 li.PersonalCustomer();
                 pClist = li.return_personal();
                 for(PersonalCustomer obj : pClist)
                 {
                     if(obj.getID().equals(idField.getText()) && obj.get_securityQ().equals(qComboBox.getItemAt(qComboBox.getSelectedIndex())) && obj.get_securityAns().equals(ansField.getText()))
                     {
                         password = obj.get_password();
                     }
                 }      
            }
            else if(tComboBox.getItemAt(tComboBox.getSelectedIndex()).equals("Staff"))
            {
                li.HubStaff();
                hSlist = li.return_hubStaff();
                 for(HubStaff obj : hSlist)
                 {
                     if(obj.getID().equals(idField.getText()) && obj.get_securityQ().equals(qComboBox.getItemAt(qComboBox.getSelectedIndex())) && obj.get_securityAns().equals(ansField.getText()))
                     {
                         password = obj.get_password();
                     }
                 }        
            }
        }
        
        if(password.equals(""))
        {
        JOptionPane.showMessageDialog(null, "ID and Security Details did not match. Please try again or contact our team.");
        
        }
        else
        {
        JOptionPane.showMessageDialog(null, "Your Password is: "+password);
        this.dispose();
        new LandingPage().setVisible(true);   
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new LandingPage().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotFrame().setVisible(true);
            }
        });
    }
    Loader li = new Loader();
    ArrayList<PersonalCustomer> pClist = new ArrayList<>();
    ArrayList<HubAdmin> hAlist = new ArrayList<>();
    ArrayList<HubStaff> hSlist = new ArrayList<>();
    ArrayList<LorryPilot> lPlist = new ArrayList<>();
    ArrayList<AirCargoPilot> aCPlist = new ArrayList<>();
    ArrayList<Owner> oWlist = new ArrayList<>();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ansField;
    private javax.swing.JLabel ansLabel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> qComboBox;
    private javax.swing.JComboBox<String> tComboBox;
    // End of variables declaration//GEN-END:variables
}
