/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import Classes.AirCargoPilot;
import Classes.HubAdmin;
import Classes.HubStaff;
import Classes.Loader;
import Classes.LorryPilot;
import Classes.PersonalCustomer;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author smart view
 */
public class PilotAccountCreatorFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form PilotAccountCreatorFrame
     */
    private boolean flag = true;
    public PilotAccountCreatorFrame(int x) {
        initComponents();
        selector = x;
        if(x==1)
        {
            salaryLabel.setVisible(false);
            salaryField.setVisible(false);   
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        selectorCombo = new javax.swing.JComboBox<>();
        fName = new javax.swing.JLabel();
        fullNameField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        hubLabel = new javax.swing.JLabel();
        dayCombo = new javax.swing.JComboBox<>();
        hubCombo = new javax.swing.JComboBox<>();
        vLabel = new javax.swing.JLabel();
        licenceField = new javax.swing.JTextField();
        licenceLabel = new javax.swing.JLabel();
        yearCombo = new javax.swing.JComboBox<>();
        vNumberField = new javax.swing.JTextField();
        salaryLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mobileLabel = new javax.swing.JLabel();
        genderCombo = new javax.swing.JComboBox<>();
        mobileNumberField = new javax.swing.JTextField();
        salaryField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        monthCombo = new javax.swing.JComboBox<>();
        dobLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        addrLabel = new javax.swing.JLabel();
        divLabel = new javax.swing.JLabel();
        divField = new javax.swing.JTextField();
        zipLabel = new javax.swing.JLabel();
        zipField = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("pilot id creator");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setText("rapido");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(632, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 622;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        selectorCombo.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        selectorCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Pilot Type", "Lorry Driver", "AirCargo Pilot" }));
        selectorCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                selectorComboFocusLost(evt);
            }
        });
        selectorCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorComboActionPerformed(evt);
            }
        });

        fName.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        fName.setText("Pilot name:");

        fullNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullNameFieldActionPerformed(evt);
            }
        });
        fullNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fullNameFieldKeyPressed(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        emailLabel.setText("Email:");

        hubLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        hubLabel.setText("Hub Location:");

        dayCombo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        dayCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day" }));
        dayCombo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dayCombo.setOpaque(false);
        dayCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dayComboFocusGained(evt);
            }
        });
        dayCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayComboActionPerformed(evt);
            }
        });

        hubCombo.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        hubCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DHAKA", "CHITTAGONG", "RAJSHAHI", "KHULNA", "BARISAL", "SYLHET", "RANGPUR" }));
        hubCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hubComboActionPerformed(evt);
            }
        });

        vLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        vLabel.setText("Vehicle Number:");

        licenceLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        licenceLabel.setText("License Number:");

        yearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));

        vNumberField.setToolTipText("Airplane ->(S2-AAAA), Lorry->(City-Class-11-1111)");
        vNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vNumberFieldActionPerformed(evt);
            }
        });
        vNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vNumberFieldKeyPressed(evt);
            }
        });

        salaryLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        salaryLabel.setText("Salary:");

        jButton1.setBackground(new java.awt.Color(0, 102, 51));
        jButton1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mobileLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        mobileLabel.setText("Mobile Number:");

        genderCombo.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        genderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Male", "Female", "Other" }));

        mobileNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileNumberFieldActionPerformed(evt);
            }
        });
        mobileNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mobileNumberFieldKeyPressed(evt);
            }
        });

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        monthCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        monthCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                monthComboFocusLost(evt);
            }
        });
        monthCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthComboActionPerformed(evt);
            }
        });

        dobLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        dobLabel.setText("Date of Birth:");

        jLabel11.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel11.setText("Gender:");

        addrLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        addrLabel.setText("Address");

        divLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        divLabel.setText("Division:");

        divField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                divFieldKeyPressed(evt);
            }
        });

        zipLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        zipLabel.setText("Zip Code:");

        zipField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                zipFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(selectorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(fName)
                        .addGap(88, 88, 88)
                        .addComponent(fullNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(addrLabel)
                        .addGap(109, 109, 109)
                        .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(vLabel)
                                .addGap(52, 52, 52)
                                .addComponent(vNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(dayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(licenceLabel)
                                .addGap(48, 48, 48)
                                .addComponent(licenceField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(hubLabel)
                                .addGap(70, 70, 70)
                                .addComponent(hubCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(mobileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(mobileNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(salaryLabel)
                                .addGap(125, 125, 125)
                                .addComponent(salaryField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(zipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(54, 54, 54)
                                    .addComponent(zipField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(divLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(82, 82, 82)
                                    .addComponent(divField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(250, 250, 250))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(selectorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(zipField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(divLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(vNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(dayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(licenceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licenceField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(hubLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hubCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mobileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(mobileNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(salaryField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70)
                .addComponent(jButton1)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 140;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void disableHubField(){
        if(selectorCombo.getSelectedItem()=="AirCargo Pilot"){
             hubCombo.setEnabled(false);
        }
        else{
            hubCombo.setEnabled(true);
        }
    }
    private void fullNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void selectorComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorComboActionPerformed
        // TODO add your handling code here:
        disableHubField();
        
    }//GEN-LAST:event_selectorComboActionPerformed

    private void hubComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hubComboActionPerformed
        // TODO add your handling code here:
        disableHubField();
    }//GEN-LAST:event_hubComboActionPerformed
    public void start_lorryPilot()
     {
        SwingWorker<Boolean,Void> worker = new SwingWorker<Boolean,Void>(){
            @Override
            public Boolean doInBackground() throws Exception{
                String fileName="LorryPilot.bin";
               File file = new File (fileName);
                ObjectOutputStream out = null;
                 boolean append=true;
                    try{
                        if (!file.exists () || !append) out =
                            new ObjectOutputStream (new FileOutputStream (fileName));
                        else out = 
                            new AppendableObjectOutputStream (new FileOutputStream (fileName, append));
                        out.writeObject(lP);
                        out.flush ();
                    }catch (Exception e){
                        //e.printStackTrace ();
                    }finally{
                        try{
                            if (out != null) out.close();
                        }catch (Exception e){
                            //e.printStackTrace();
                        }
        }
             //Get properties object    
          Properties props = new Properties();    
          props.put("mail.smtp.host", "smtp.gmail.com");    
          props.put("mail.smtp.socketFactory.port", "465");    
          props.put("mail.smtp.socketFactory.class",    
                    "javax.net.ssl.SSLSocketFactory");    
          props.put("mail.smtp.auth", "true");    
          props.put("mail.smtp.port", "465");    
          //get Session   
          Session session = Session.getDefaultInstance(props,    
           new javax.mail.Authenticator() {    
           protected PasswordAuthentication getPasswordAuthentication() {    
           return new PasswordAuthentication("rapidoteam2018@gmail.com","7951384620");  
           }    
          });    
          //compose message    
          try {    
           MimeMessage message = new MimeMessage(session);    
           message.addRecipient(Message.RecipientType.TO,new InternetAddress(emailField.getText()));    
           message.setSubject("Confirmation of Account Creation");    
           message.setText("Dear Mr"+fullNameField.getText()+",\n\nWelcome to the Rapidoo Team. Your ID is: "+id+".\n\nWe look to working with you. \n\n Your's Sincerely, \n\n Rapido Team");    
           //send message  
           Transport.send(message);   
          } catch (MessagingException e) {throw new RuntimeException(e);}
                return true;
            }

           
        };
        worker.execute(); 
     }
    
    public void start_airCargoPilot()
     {
        SwingWorker<Boolean,Object[]> worker = new SwingWorker<Boolean,Object[]>(){
            @Override
            public Boolean doInBackground() throws Exception{
                String fileName="AirCargoPilot.bin";
               File file = new File (fileName);
                ObjectOutputStream out = null;
                 boolean append=true;
                    try{
                        if (!file.exists () || !append) out =
                            new ObjectOutputStream (new FileOutputStream (fileName));
                        else out = 
                            new AppendableObjectOutputStream (new FileOutputStream (fileName, append));
                        out.writeObject(aCP);
                        out.flush ();
                    }catch (Exception e){
                        //e.printStackTrace ();
                    }finally{
                        try{
                            if (out != null) out.close();
                        }catch (Exception e){
                            //e.printStackTrace();
                        }
        }
             //Get properties object    
          Properties props = new Properties();    
          props.put("mail.smtp.host", "smtp.gmail.com");    
          props.put("mail.smtp.socketFactory.port", "465");    
          props.put("mail.smtp.socketFactory.class",    
                    "javax.net.ssl.SSLSocketFactory");    
          props.put("mail.smtp.auth", "true");    
          props.put("mail.smtp.port", "465");    
          //get Session   
          Session session = Session.getDefaultInstance(props,    
           new javax.mail.Authenticator() {    
           protected PasswordAuthentication getPasswordAuthentication() {    
           return new PasswordAuthentication("rapidoteam2018@gmail.com","7951384620");  
           }    
          });    
          //compose message    
          try {    
           MimeMessage message = new MimeMessage(session);    
           message.addRecipient(Message.RecipientType.TO,new InternetAddress(emailField.getText()));    
           message.setSubject("Confirmation of Account Creation");    
           message.setText("Dear Mr"+fullNameField.getText()+",\n\nWelcome to the Rapidoo Team. Your ID is: "+id+".\n\nWe look to working with you. \n\n Your's Sincerely, \n\n Rapido Team");    
           //send message  
           Transport.send(message);   
          } catch (MessagingException e) {throw new RuntimeException(e);}
                return true;
            }

            @Override
            public void process(List<Object[]> obj){
               // result.setText(result.getText()+"No of Student of "+obj.get(0)[0].toString()+" Dept: "+Integer.parseInt(obj.get(0)[1].toString())+"\n");
            }
            
            @Override
            public void done() {
                boolean done=false;
                try {
                    done = get();
                } catch(Exception ex) {
                    ex.printStackTrace();
                }
                if(done){
                    //statusLabel.setText("Text Files are created successfully");
                }else{
                    //statusLabel.setText("Text Files creation Failed");
                }
            }
        };
        worker.execute(); 
     }
    
    class AppendableObjectOutputStream extends ObjectOutputStream {
       public AppendableObjectOutputStream(OutputStream out) throws IOException {
        super(out);
    }
  @Override
    protected void writeStreamHeader() throws IOException {}
    
  }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           //id
      String prev_id;
      //checkbools
      boolean name = false, em = false, addr = false, zipCode = false, division = false, dob = false, gender = false, mobile = false;
      //loadArrays
      li.LorryPilot();
      li.airCargoPilot();
      li.loadAllEmails();
      aCPlist = li.return_pilot();
      lPlist = li.return_lorry();
      emailList = li.return_AllEmails();
      
      //namecheck
      if(fullNameField.getText().equals(""))
      {
          fName.setForeground(Color.red);
          fullNameField.requestFocus();
      }
      else
      {
          name = true;
          fName.setForeground(Color.black);
      }
      //emailFieldCheck
      if(emailField.getText().equals(""))
      {
          emailLabel.setForeground(Color.red);
          emailField.requestFocus();
      }
      else
      {
          em = true;
          emailLabel.setForeground(Color.black);
      }
      //emailExistCheck
      if(!emailList.isEmpty())
      {
          for(String emails : emailList)
          {
              if(emailField.getText().equals(emails))
              {
                  emailField.setForeground(Color.red);
                  em = false;
                  emailField.requestFocus();
                  break;
              }
              else
              {
                  emailField.setForeground(Color.black);
              }
          }
      }
      //addressCheck
      if(addressField.getText().equals(""))
      {
          addrLabel.setForeground(Color.red);
          addressField.requestFocus();
      }
      else
      {
          addr = true;
          addrLabel.setForeground(Color.black);
      }
      //zipCheck
      if(zipField.getText().equals(""))
      {
          zipLabel.setForeground(Color.red);
          zipField.requestFocus();
      }
      else
      {
          zipCode = true;
          zipLabel.setForeground(Color.black);
      }
      //divisionCheck
      if(divField.getText().equals(""))
      {
          divLabel.setForeground(Color.red);
          divField.requestFocus();
      }
      else
      {
          division = true;
          divLabel.setForeground(Color.black);
      }
      //dobCheck 
          if(dayCombo.getSelectedIndex() ==0)
          {
              dobLabel.setForeground(Color.red);
              dayCombo.requestFocus();
          }
          
          if(monthCombo.getSelectedIndex()==0)
          {
              dobLabel.setForeground(Color.red);
              monthCombo.requestFocus();
          }
        
          
          if(yearCombo.getSelectedIndex() ==0)
          {
              dobLabel.setForeground(Color.red);
              yearCombo.requestFocus();
          }

       if(dayCombo.getSelectedIndex() >0 && monthCombo.getSelectedIndex() >0 && yearCombo.getSelectedIndex() > 0)
      {
          dobLabel.setForeground(Color.black);
          dob = true;
      }
  
      //checkGender
      if(genderCombo.getSelectedIndex() == 0)
      {
         genderCombo.requestFocus();
      }
      else
      {
         gender = true; 
      }
      //checkMobile
      if(mobileNumberField.getText().equals(""))
      {
          mobileLabel.setForeground(Color.red);
          mobileLabel.requestFocus();
      }
      else if(mobileNumberField.getText().length()!=11)
      {
          mobileLabel.setForeground(Color.red);
          mobileLabel.requestFocus();
      }
      else
      {
          mobileLabel.setForeground(Color.black);
          mobile = true;
      }
      //createAccount
      if(name == true && em == true && addr == true && zipCode == true && division == true && dob == true &&  gender == true && mobile == true)
      {
          if(selectorCombo.getSelectedIndex() ==1)
          {
          if(lPlist.isEmpty())
          {
              id = "FEDEXLP0";
          }
          else
          {
              prev_id = lPlist.get(lPlist.size()-1).getID();
              String[] split = prev_id.split("LP");
              int number = Integer.parseInt(split[1]);
              number++;
              id = "FEDEXLP"+number;
          }
          }
          else 
          {
             if(aCPlist.isEmpty())
          {
              id = "FEDEXACP0";
          }
          else
          {
              prev_id = aCPlist.get(aCPlist.size()-1).getID();
              String[] split = prev_id.split("ACP");
              int number = Integer.parseInt(split[1]);
              number++;
              id = "FEDEXACP"+number;
          } 
          }
          String d = ""; 
          LocalDate date;
           d = d + yearCombo.getItemAt(yearCombo.getSelectedIndex())+"-";
           d = d + monthCombo.getItemAt(monthCombo.getSelectedIndex()) +"-";
           d = d + dayCombo.getItemAt(dayCombo.getSelectedIndex());
          date = LocalDate.parse(d);
          if(selectorCombo.getSelectedIndex()==1)
          {
          lP = new LorryPilot();
          lP.createLorryPilot(id, fullNameField.getText(), mobileNumberField.getText(), addressField.getText(), divField.getText(), emailField.getText(), Integer.parseInt(zipField.getText()), genderCombo.getItemAt(genderCombo.getSelectedIndex()), date, hubCombo.getItemAt(hubCombo.getSelectedIndex()), licenceField.getText(), vNumberField.getText(), 15000);
          start_lorryPilot();
          JOptionPane.showMessageDialog(null, "New Lorry Pilot Account Created \n Your Login id is "+id, "Success", JOptionPane.INFORMATION_MESSAGE);
          }
          else
          {
          aCP = new AirCargoPilot();
          aCP.createAirCargoPilot(id, fullNameField.getText(), mobileNumberField.getText(), addressField.getText(), divField.getText(), emailField.getText(), Integer.parseInt(zipField.getText()), genderCombo.getItemAt(genderCombo.getSelectedIndex()), date, licenceField.getText(), vNumberField.getText(), 150000);
          start_airCargoPilot();
          JOptionPane.showMessageDialog(null, "New Air Cargo Pilot Account Created \n Your Login id is "+id, "Success", JOptionPane.INFORMATION_MESSAGE); 
          }
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void monthComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthComboFocusLost

    }//GEN-LAST:event_monthComboFocusLost

    private void monthComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthComboActionPerformed

    }//GEN-LAST:event_monthComboActionPerformed

    private void dayComboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dayComboFocusGained
        int month = monthCombo.getSelectedIndex();
        dayCombo.removeAllItems();
        dayCombo.addItem("Day");
        if(month == 1 || month == 3 || month==5 || month==7 || month==8 || month==10 || month==12 )
        {
            for(int i =1; i<=31; i++)
            {
               if(i<10)
                {
                dayCombo.addItem("0"+Integer.toString(i));
                }
                else
                {
                 dayCombo.addItem(Integer.toString(i));
                }
            }
        }
        else if(month==4 || month==6 || month ==9 || month==11)
        {
            for(int i =1; i<=30; i++)
            {
               if(i<10)
                {
                dayCombo.addItem("0"+Integer.toString(i));
                }
                else
                {
                 dayCombo.addItem(Integer.toString(i));
                }
            }
        }
        else if(month==2)
        {
            int year = Integer.parseInt(yearCombo.getItemAt(yearCombo.getSelectedIndex()));
            if((year%4==0 && year%100!=0) || (year%100==0 && year%400==0))
            {
                for(int i =1; i<=29; i++)
                {
                   if(i<10)
                {
                dayCombo.addItem("0"+Integer.toString(i));
                }
                else
                {
                 dayCombo.addItem(Integer.toString(i));
                }
                }
            }
            else
            {
                for(int i =1; i<=28; i++)
                {
                    if(i<10)
                {
                dayCombo.addItem("0"+Integer.toString(i));
                }
                else
                {
                 dayCombo.addItem(Integer.toString(i));
                }
                }
            }
        }
    }//GEN-LAST:event_dayComboFocusGained

    private void dayComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayComboActionPerformed

    }//GEN-LAST:event_dayComboActionPerformed

    private void fullNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fullNameFieldKeyPressed
        int key = evt.getKeyCode();
        if((key>=evt.VK_A && key<=evt.VK_Z) || key==evt.VK_PERIOD || key==evt.VK_SPACE || key==evt.VK_BACK_SPACE || key==evt.VK_QUOTE)
        {
            fullNameField.setEditable(true);
        }
        else
        {
            fullNameField.setEditable(false);
        }
    }//GEN-LAST:event_fullNameFieldKeyPressed

    private void vNumberFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vNumberFieldKeyPressed
        int key = evt.getKeyCode();
        if(selectorCombo.getSelectedIndex()==1)
        {
        if((key>=evt.VK_A && key<=evt.VK_Z) || key==evt.VK_SUBTRACT || key ==evt.VK_MINUS || key==evt.VK_BACK_SPACE)
        {
            vNumberField.setEditable(true);
        }
        else
        {
            vNumberField.setEditable(false);
        }
        }
    }//GEN-LAST:event_vNumberFieldKeyPressed

    private void selectorComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selectorComboFocusLost

    }//GEN-LAST:event_selectorComboFocusLost

    private void mobileNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileNumberFieldActionPerformed

    private void mobileNumberFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileNumberFieldKeyPressed
        int key = evt.getKeyCode();
        if(key==evt.VK_BACK_SPACE || ((key>=evt.VK_0&&key<=evt.VK_9)) || (key>=evt.VK_NUMPAD0&&key<=evt.VK_NUMPAD9))
        {
            mobileNumberField.setEditable(true);
        }
        else
        {
            mobileNumberField.setEditable(false);
        }
    }//GEN-LAST:event_mobileNumberFieldKeyPressed

    private void divFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_divFieldKeyPressed
        int key = evt.getKeyCode();
        if((key>=evt.VK_A && key<=evt.VK_Z) || key==evt.VK_BACK_SPACE )
        {
            divField.setEditable(true);
        }
        else
        {
            divField.setEditable(false);
        }
    }//GEN-LAST:event_divFieldKeyPressed

    private void zipFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zipFieldKeyPressed
        int key = evt.getKeyCode();
        if(key>=evt.VK_0&&key<=evt.VK_9 || key>=evt.VK_NUMPAD0&&key<=evt.VK_NUMPAD9 || key==KeyEvent.VK_BACKSPACE)
        {
            zipField.setEditable(true);
        }
        else
        {
            zipField.setEditable(false);
        }
    }//GEN-LAST:event_zipFieldKeyPressed

    private void vNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vNumberFieldActionPerformed
Loader li = new Loader();
LorryPilot lP;
AirCargoPilot aCP;
ArrayList<LorryPilot> lPlist = new ArrayList<>();
ArrayList<AirCargoPilot> aCPlist = new ArrayList<>();
ArrayList<String> emailList = new ArrayList<>();
String id = "";
int selector = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addrLabel;
    private javax.swing.JTextField addressField;
    private javax.swing.JComboBox<String> dayCombo;
    private javax.swing.JTextField divField;
    private javax.swing.JLabel divLabel;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel fName;
    private javax.swing.JTextField fullNameField;
    private javax.swing.JComboBox<String> genderCombo;
    private javax.swing.JComboBox<String> hubCombo;
    private javax.swing.JLabel hubLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField licenceField;
    private javax.swing.JLabel licenceLabel;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JTextField mobileNumberField;
    private javax.swing.JComboBox<String> monthCombo;
    private javax.swing.JTextField salaryField;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JComboBox<String> selectorCombo;
    private javax.swing.JLabel vLabel;
    private javax.swing.JTextField vNumberField;
    private javax.swing.JComboBox<String> yearCombo;
    private javax.swing.JTextField zipField;
    private javax.swing.JLabel zipLabel;
    // End of variables declaration//GEN-END:variables
}
